version: '2'

services:

  riak:
    image: tapjoy/docker-riak
    networks:
      tapjoy.localdev:
    volumes:
      - riak:/var/lib/riak

networks:
  tapjoy.localdev:
    external: true

volumes:
  riak:
